### ISSUE TITLE
Add attribution

### ISSUE THREAD

**Issue by leo** [heiswayi/the-plain#1]
I'm very honored that you're using my Jekyll theme as a base for yours. But I also need to remind you that my site's source is licensed under [MIT](https://github.com/leo/leo.github.io/blob/master/LICENSE), which basically means you'll have to provide some kind of attribution back to me, if you want to keep using it.

Thank you!

**Comment by heiswayi** [comment]
Thanks for remind me, here I just updated the [README.md](https://github.com/heiswayi/the-plain/blob/master/README.md) file providing the attribution link back to you.

**Comment by leo** [comment]
👍
