### ISSUE TITLE
Forking Project

### ISSUE THREAD

**Issue by efe** [heiswayi/the-plain#10]
I have already a jekyll site working on the main domain (_efe.github.io_). I want to use this theme as a project. Firstly, I have forked the project. Secondly, I have chanced the baseurl in __config.yml_. However, _efe.github.io/the-plain_ looks 404 (page not found).

Where am i missing?

**Comment by heiswayi** [comment]
You may need to create a new branch called `gh-pages`, and make sure your `baseurl` in **_config.yml** is written in correct format.
