### ISSUE TITLE
Footnotes not parsing

### ISSUE THREAD

**Issue by tionosulis** [heiswayi/the-plain#19]
Firstly thankyou for the such simple-great theme. I'm attempting to use footnotes on my test post, instead of showing just like how it works on the theme demo page, the footnotes on my test post (link https://sulis-tiono.github.io/notes/Alternative-async-Google-Analytics-Tracking-Snippet) seem doesn't work and not parsing corectly thus he footnote definition does not appear. Did I miss something? Any help would be much appreciated.

Regards,
Sulistiono

**Comment by heiswayi** [comment]
Thanks for using this theme. I updated the source code to **version 2.2**, no longer using footnote script. Instead, the footnotes will be displayed in classical way, which at the bottom of the content. Please check here for the demo: [http://heiswayi.github.io/the-plain/notes/very-long-title-post](http://heiswayi.github.io/the-plain/notes/very-long-title-post)

**Comment by tionosulis** [comment]
Thankyou for the quick workaround, updated the source to ver 2.2 and the issue fixed. You guys Rock !

Salam
Sulistiono
