### ISSUE TITLE
Sharing ribbon

### ISSUE THREAD

**Issue by missingfaktor** [heiswayi/the-plain#22]
Hello! Really love the plain theme. Great work. 🙂 Would it be possible to provide a sharing ribbon underneath posts? Or, would that go against the minimalist philosophy of this theme?

**Comment by heiswayi** [comment]
Thanks for using The Plain. Customizing the theme is totally up to you.. it's a personal taste. But if you really want to maintain minimalist look, it's best to design or place sharing buttons with minimalist look too.
