### ISSUE TITLE
prompts don't line up in Safari

### ISSUE THREAD

**Issue by thenerdlawyer** [heiswayi/the-plain#3]
In Chrome, the floating prompts work beautifully:
![screen shot 2015-11-07 at 5 43 53 pm](https://cloud.githubusercontent.com/assets/10391323/11017734/48a250cc-8577-11e5-87c1-da046ef63612.png)
![screen shot 2015-11-07 at 5 44 03 pm](https://cloud.githubusercontent.com/assets/10391323/11017736/4cb6713e-8577-11e5-8d7f-75f207dedd37.png)

However, in Safari they appear in the middle of the page:

![screen shot 2015-11-07 at 5 44 33 pm](https://cloud.githubusercontent.com/assets/10391323/11017741/5f3db88a-8577-11e5-9a41-06799e1fec4f.png)
![screen shot 2015-11-07 at 5 44 44 pm](https://cloud.githubusercontent.com/assets/10391323/11017742/5f43c73e-8577-11e5-9dda-f2667a32356c.png)

**Comment by tcitry** [comment]
meet the same problem on Safari 9.0.2 (11601.3.9)

**Comment by llllvvuu** [comment]
I saw this on Chrome as well. Don't know if the author is still active but it's a simple CSS fix, you can go to PR #14 and apply it for yourself
