### ISSUE TITLE
cdn.mathjax.org has been retired

### ISSUE THREAD

**Issue by cemremengu** [heiswayi/the-plain#36]
⚠️
 cdn.mathjax.org has been retired. Check https://www.mathjax.org/cdn-shutting-down/ for migration tips.

**Comment by heiswayi** [comment]
thanks for mentioning that.
this theme already been using cdn from cloudflare for mathjax:
https://github.com/heiswayi/the-plain/blob/master/_includes/head.html

**Comment by cemremengu** [comment]
I see, I downloaded the last release thats why I didnt get the changes
