### ISSUE TITLE
Last update killed all my website

### ISSUE THREAD

**Issue by Korbeil** [heiswayi/the-plain#41]
Hi, last "major redesign" commit killed a lot of style I have on my website:
- Website: https://baptiste-leduc.now.sh/
- Repo: https://github.com/Korbeil/website

Is there a way to avoid using last release and use use before that commit ?

**Comment by Korbeil** [comment]
Fixed by doing: https://github.com/Korbeil/website/commit/3e37b61c1fd3fed1d8a7791ce0adc861982cdb26

Could you implement some tags to make it easier to switch between theses changes ?

**Comment by heiswayi** [comment]
Hi. sorry for that, i have made a tag for previous commit before the "major redesign". check it here: https://github.com/heiswayi/the-plain/releases/tag/v3.1.0

**Comment by Korbeil** [comment]
Thanks ! I used the tag to make it cleaner :) (cf. https://github.com/Korbeil/website/commit/b20cc476c7e1966189af44a46f9ea1562334f95b)

Again, thanks a lot for your theme ! ;)
