### ISSUE TITLE
bundler (~> 1.15) version too low

### ISSUE THREAD

**Issue by nimohunter** [heiswayi/the-plain#44]
Hi,
Thanks for this awesome jekyll theme.
When clone this theme and [build this by docker](https://github.com/envygeeks/jekyll-docker) found some error, here is the error message:

> Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    bundler (~> 1.15)

>  Current Bundler version:
>    bundler (2.0.2)
> This Gemfile requires a different version of Bundler.
> Perhaps you need to update Bundler by running `gem install bundler`?
> Could not find gem 'bundler (~> 1.15)' in any of the relevant sources:
  the local ruby installation

so i find ./the-plain.gemspec choose the low version of bundler and rake, so maybe upgrade the version of bundler and rake?

I'll send a pull request...
Thank you!

**Comment by bisangle** [comment]
Hi,guys
      I also encountered the same problem.But i solved it.
      You can change the the-plain.gemspec bundle version to your own system version.

**Comment by kiicat** [comment]
Hi,guys
I also encountered the same problem.But i solved it.
You can change the the-plain.gemspec bundle version to your own system version.
`spec.add_development_dependency "bundler", "~> 2.0.2"`

**Comment by nimohunter** [comment]
@bisangle  yes, you are right.  this version of bundler is lower with that in jekyll offical docker image. so you can edit like this [pull request](https://github.com/heiswayi/the-plain/pull/45/files)
