### ISSUE TITLE
code highlighting not working

### ISSUE THREAD

**Issue by ahjumma** [heiswayi/the-plain#5]
Hello, I am trying to highlight my code using your template Jekyll theme and I realized that code highlighting does not get processed from the page. 

The funny thing is that this markdown formatting is properly processed when you view the markdown file directly from the github page. 

Your provided _config.yml is as followed. 
"""
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed
"""
I have researched and from my current understanding I can't find anything wrong with your _config.yml file..

**Comment by heiswayi** [comment]
to make the syntax highlighting works, try using this:

```
markdown:           redcarpet
redcarpet:
    extensions:     ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "highlight", "footnotes"]
```

instead of

```
#markdown:           kramdown
#kramdown:
#    input:          GFM
```

but when you use `redcarpet`, **the footnote popup will not work**. im still looking into this. will fix it in future.
