### ISSUE TITLE
the about pages 404

### ISSUE THREAD

**Issue by beepony** [heiswayi/the-plain#9]
when I forked the plain, git clone to my computer and when I visited the about pages, it shows 404, but I can see the file. here is some picture about the issue. PS. I didn't modified any file~
![snip20160112_137](https://cloud.githubusercontent.com/assets/7813288/12260103/c00a0504-b954-11e5-951f-424e26886343.png)

![snip20160112_138](https://cloud.githubusercontent.com/assets/7813288/12260153/15e79810-b955-11e5-846a-bfefce6f4dea.png)

**Comment by heiswayi** [comment]
inside `about.md`, try add this before `title`:

**layout: page**

**Comment by beepony** [comment]
Thanks a lot. I've tried, but it just does't work ~
![image](https://cloud.githubusercontent.com/assets/7813288/12283642/3a3a75aa-b9e3-11e5-9987-6c9bb4ba400a.png)

**Comment by beepony** [comment]
Do you have tested the issue? Is it the same as I am~

**Comment by beepony** [comment]
I think I found the issue. in `_site` dir you may mkdir a about dir and mv the about.html into it, and rename it index.html. that's it
